Repository TheRealAstoo/spotify-project, pull requests merged in 2020-11, with the labels that each got.

#3 added some implementation on the current track play
  src/pages/player.tsx
Labels: BACK, good first issue

#4 btn next and previous player
  src/pages/player.tsx
Labels: BACK

#6 UI navbar
  public/HomeLogo.png
  public/ParcourirLogo.png
  public/RadioLogo.png
  public/globals.css
  public/homelogo.jpg
  public/logo.png
  src/components/Layout.tsx
  src/components/LeftBloc.tsx
  src/components/Nav.tsx
  src/pages/_app.tsx
  src/pages/parcourir.tsx
  src/pages/radio.tsx
  yarn.lock
Labels: FRONT

#5 pushing my first version of the play button
  src/pages/player.tsx
Labels: BACK, good first issue, invalid, wontfix

#8 the previous btn is back baby
  src/pages/player.tsx
Labels: BACK, duplicate

#9 Thanks to Fenn we have now a good play/pause btn :p
  public/globals.css
  src/pages/player.tsx
  src/styles/global.css
Labels: BACK, duplicate, enhancement

#12 ajout de bootstrap
  package.json
  src/components/LecteurFooter.tsx
  src/pages/_app.tsx
  src/pages/player.tsx
  src/styles/LecteurFooter.css
  yarn.lock
Labels: FRONT

#13 part 1 de la liste des musiques de l'album données en dur
  src/components/Layout.tsx
  src/components/LeftBloc.tsx
  src/components/MainContainer.tsx
  src/components/TracksList.tsx
  src/pages/_app.tsx
  src/pages/parcourir.tsx
  src/pages/player.tsx
  src/pages/radio.tsx
  src/styles/globals.css
Labels: BACK

#11 added the position in music stream and progress bar first style
  package.json
  src/pages/player.tsx
Labels: BACK, FRONT, enhancement

#14 transfert vers le pc de louis
  src/components/LecteurFooter.tsx
  src/components/MainContainer.tsx
  src/components/MusicControls.tsx
  src/pages/index.tsx
  src/pages/player.tsx
Labels: FRONT

#15 Affichage dynamique de l'album(juste les nom des musique)
  src/components/MainContainer.tsx
  src/components/TracksList.tsx
  src/pages/player.tsx
  src/types/spotify.d.ts
Labels: BACK

#16 added a new architecture to the project and some style
  src/components/Layout.tsx
  src/components/MainContainer.tsx
  src/components/MusicControls.tsx
  src/components/NavSideBar.tsx
  src/pages/_app.tsx
  src/pages/player.tsx
  src/styles/global.css
  src/styles/globals.css
Labels: BACK, FRONT, enhancement

#17 ajout du nom du ou des artiste(s) et l'index du morceau
  src/components/TracksList.tsx
Labels: BACK, FRONT

#18 undone some suppressions made to fast
  src/components/MainContainer.tsx
  src/components/TracksList.tsx
  src/pages/player.tsx
Labels: FRONT

#19 added some style on the lecteur
  package.json
  src/components/MainContainer.tsx
  src/pages/player.tsx
  src/styles/global.css
  src/styles/globals.css
  yarn.lock
Labels: FRONT

#21 je suis une belle grosse merde
  src/components/TracksList.tsx
  src/pages/player.tsx
  src/styles/globals.css
Labels: BACK, FRONT

#20 Feature/shuffle btns
  src/pages/_app.tsx
  src/pages/player.tsx
  src/styles/global.css
  src/styles/globals.css
Labels: BACK, FRONT

#22 Creation du bouton repeat et ajout de l'image de la musique
  src/components/NavSideBar.tsx
  src/components/TracksList.tsx
  src/pages/player.tsx
  src/styles/global.css
Labels: BACK, FRONT

#23 added some style and done some types (not finished)
  src/components/NavSideBar.tsx
  src/components/TracksList.tsx
  src/pages/player.tsx
  src/styles/global.css
  src/types/spotify.d.ts
Labels: BACK, FRONT, bug, invalid

#24 added the album display feature
  src/components/NavSideBar.tsx
  src/components/TracksList.tsx
  src/pages/player.tsx
Labels: BACK, FRONT

#25 added the sound changes
  src/components/TracksList.tsx
  src/pages/player.tsx
Labels: BACK, FRONT

#27 added few styles on sound buttons
  src/pages/player.tsx
  src/styles/global.css
Labels: FRONT

#28 Ajout des icones de la NavSideBar
  src/components/Layout.tsx
  src/components/NavSideBar.tsx
  src/pages/player.tsx
  src/styles/global.css
Labels: FRONT

#29 weeeee aaaaaare theeee chaaaampioooooons
  src/components/TracksList.tsx
  src/pages/player.tsx
  src/styles/global.css
  src/types/spotify.d.ts
Labels: BACK, FRONT
